export const PROCEDURES = {
  LOGIN: 'sp_DashboardLogin',
  GET_STEPS_USER: 'sp_UserGetSteps',
  VALIDATE_AUTHORIZATION_CODE: 'sp_UserValidateAuthorizationCode',
  GET_PASSWORD: 'sp_UserGetPassword',
  CHANGES_PASSWORD: 'sp_UserChangePassword',
  GET_COMPANIES: 'sp_CompanyGetAll',
  GET_COMPANY_BY_ID: 'sp_CompanyGetById',
  CREATE_COMPANY: 'sp_CompanyCreateOrUpdate',
  // UPDATE_COMPANY: 'sp_CompanyUpdate',
  /*//
  GET_COUNTRIES: 'sp_CountryGetAll',
  GET_COUNTRY_BY_ID: 'sp_CountryGetById',
  CREATE_COUNTRY: 'sp_CountryCreate',
  UPDATE_COUNTRY: 'sp_CountryUpdate',
  //
  GET_CITIES: 'sp_CityGetAll',
  GET_CITY_BY_ID: 'sp_CityGetById',
  CREATE_CITY: 'sp_CityCreate',
  UPDATE_CITY: 'sp_CityUpdate',
  //*/
  // GET_STEPS: 'sp_StepGetAll',
  GET_STEP_BY_ID: 'sp_StepGetById',
  UPDATE_STEP: 'sp_StepUpdate',
  DASHBOARD_DATA: 'sp_GetDataOfDashboard',
  GET_USERS: 'sp_UserGetAll',
  CREATE_USER: 'sp_UserCreate',
  UPDATE_USER: 'sp_UserUpdate',
  GET_EMPLOYEES: 'sp_EmployeeGetAll',
  CREATE_EMPLOYEE: 'sp_CreatedEmployee',
  UPDATE_EMPLOYEE: 'sp_EmployeeUpdate',
  DASHBOARD_PAYMENTS_DATA: 'sp_DashboardPaymentsData',
  GET_PAYMENTS: 'sp_PaymentGetAll',
  GET_PAYMENT_BY_ID: 'sp_getPaymentById',
  GET_DATA_SEND_BOLETO_ORNATO: 'sp_BoletoOrnato_GetDataSend',
  GET_ROLES: 'sp_RoleGetAll',
  CREATE_ROLE: 'sp_RoleCreate',
  UPDATE_ROLE: 'sp_RoleUpdate',
  GET_PERMISSIONS: 'sp_PermissionGetAll',
  GET_PERMISSIONS_BY_ROLE: 'sp_GetPermissionsByRole',
  GET_ROLES_WITH_DETAILS: 'sp_GetRolesWithDetails',
  GET_PROFILE: 'sp_ProfileGet',
  UPDATED_PROFILE: 'sp_ProfileUpdate',
  GET_ALL_DEVICES_OF_2FA: 'sp_2FAGetAllDevices',
  CREATE_NEW_DEVICE_2FA: 'sp_2FACreateNewDevice',
  DELETE_DEVICE_2FA: 'sp_2FADeleteDevice',
  GET_ACTIVE_SESSIONS: 'sp_SessionGetActive',
  CLOSE_SESSION: 'sp_SessionClose',
  CREATE_SESSION: 'sp_SessionCreate',
  CLOSE_ALL_SESSIONS: 'sp_SessionCloseAll',
  CLOSE_DEVICE_SESSIONS: 'sp_SessionCloseDeviceSessions',
  UPDATE_SESSION_ACTIVITY: 'sp_SessionUpdateActivity',
  GET_SESSION_HISTORY: 'sp_SessionGetHistory',
  SAVE_SIGNATURE: 'sp_SignatureSave',
  CHANGES_SIGNATURE: 'sp_SignatureChange',
  LOGOUT: 'sp_UserLogout',
  SIGN_PAYMENT_ON_BEHALF: 'sp_SignPaymentOnBehalf'
}
